import Link from "next/link";
import { AppointmentCard, Arrow, PageHero, StandardPage } from "../components";
import Testimonials from "./testimonials";
export default function Retraites() {
  return <StandardPage><PageHero eyebrow="Cercle · Retraites spirituelles" title={<>Un voyage<br />au cœur de soi.</>} lead="Des espaces-temps confidentiels pour ralentir, se déposer et renouer avec une présence plus profonde." />
    <section className="gallery shell"><div className="gallery__large" /><div className="gallery__stack"><div className="gallery__small one" /><div className="gallery__small two" /></div></section>
    <section className="retreat-moments section shell" aria-labelledby="retreat-moments-title">
      <div className="retreat-moments__heading">
        <p className="eyebrow">Vivre la retraite</p>
        <h2 id="retreat-moments-title">Des instants<br /><em>hors du temps.</em></h2>
        <p>De la profondeur des pratiques à la douceur des soirées, chaque moment participe au voyage.</p>
      </div>
      <div className="retreat-moments__grid">
        <figure className="retreat-moment retreat-moment--practice"><img src="/retreat-practice.jpg" alt="Femmes allongées pendant un temps de pratique corporelle à Villa Maya" /><figcaption><span>01</span><p>Se déposer<br /><em>dans le corps</em></p></figcaption></figure>
        <figure className="retreat-moment retreat-moment--terrace"><img src="/retreat-terrace.jpeg" alt="Terrasse et piscine de Villa Maya au crépuscule" /><figcaption><span>02</span><p>Habiter la douceur<br /><em>du soir</em></p></figcaption></figure>
        <figure className="retreat-moment retreat-moment--fire"><img src="/retreat-fire.jpeg" alt="Cercle de femmes réuni autour du feu dans le jardin" /><figcaption><span>03</span><p>Se relier<br /><em>autour du feu</em></p></figcaption></figure>
      </div>
    </section>
    <section className="shell section retreat-intro"><div><p className="eyebrow">Villa Maya · Essaouira</p><h2>Rebirth &<br /><em>Kundalini</em></h2></div><div><p>Dans un écrin de pierre et de nature près de Sidi Kaouki, Cercle propose des retraites en petit groupe. Le programme articule souffle conscient, kundalini, méditation, exploration somatique, temps de parole et intégration.</p><p>Chaque proposition est encadrée avec attention. Une rencontre préalable permet de vérifier que l’expérience correspond à votre situation.</p><Link href="/rendez-vous?motif=retraite" className="button">Recevoir le programme <Arrow /></Link></div></section>
    <section className="annual-retreats section"><div className="shell">
      <div className="annual-retreats__intro"><div><p className="eyebrow">Deux rendez-vous par an</p><h2>Deux retraites.<br /><em>Deux expériences uniques.</em></h2></div><div className="annual-retreats__promise"><p>Il existe des moments où continuer comme avant n’est plus possible. Des moments où l’on ressent le besoin de sortir du bruit, de revenir au corps et d’écouter enfin les questions que le quotidien laisse sans réponse.</p><p>Deux fois par an, Villa Maya devient cet espace de passage : une retraite réservée aux femmes et une retraite mixte. Quelques jours à part, dans un groupe intime, pour ralentir, ressentir et laisser émerger une manière plus libre d’habiter sa vie.</p></div></div>
      <div className="session-grid">
        <article className="session-card session-card--women"><span>Session 01 · Printemps</span><h3>Le Cercle<br />des femmes</h3><p>Un espace entre femmes pour déposer ce que l’on porte depuis trop longtemps, retrouver la voix du corps et renouer avec une puissance qui n’a rien à prouver. Ici, la parole peut être vraie, le silence pleinement habité et la vulnérabilité devenir une force.</p><ul><li>Groupe intime et confidentiel</li><li>Pratiques adaptées au rythme de chacune</li><li>Temps de cercle et d’intégration</li></ul></article>
        <article className="session-card session-card--mixed"><span>Session 02 · Automne</span><h3>Le Cercle<br />du vivant</h3><p>Une retraite ouverte aux femmes et aux hommes pour sortir des automatismes, rencontrer l’autre autrement et retrouver une présence plus consciente. Les différences deviennent un miroir, les pratiques ouvrent de nouveaux possibles et chacun avance sans masque, à son rythme.</p><ul><li>Femmes et hommes</li><li>Équilibre entre pratiques et temps libres</li><li>Cadre sécurisant et bienveillant</li></ul></article>
      </div>
    </div></section>
    <section className="immersive-program"><div className="shell immersive-program__head"><p className="eyebrow light">Une expérience complète</p><h2>Prendre soin.<br /><em>Respirer. Ressentir.</em></h2><p>Le programme est une invitation, jamais une contrainte. Chacun participe selon son énergie, ses besoins et ce qu’il se sent prêt à explorer.</p></div><div className="shell experience-grid">
      {[["01","Soins & massages","Des temps de soin pour relâcher les tensions, habiter pleinement le corps et retrouver une sensation profonde d’apaisement."],["02","Danse & mouvement","Une exploration libre et guidée pour laisser circuler l’énergie, retrouver de la spontanéité et remettre le vivant en mouvement."],["03","Méditation","Des pratiques accessibles pour ralentir le mental, cultiver la présence et ouvrir un espace intérieur plus vaste."],["04","Kundalini","Un travail énergétique mêlant respiration, mouvement, son et attention pour réveiller la vitalité et la conscience corporelle."],["05","Rebirth","Une respiration consciente et accompagnée pour traverser les émotions, libérer ce qui demande à l’être et retrouver un nouvel élan."],["06","Yoga","Des séances adaptées au groupe pour délier le corps, soutenir l’ancrage et préparer les temps d’exploration intérieure."],["07","Reconnexion à soi","Des temps d’écriture, de silence, de partage et d’intégration pour écouter ses besoins et retrouver son propre chemin."],["08","Cercle de parole","Un espace confidentiel, sans jugement, où la parole peut se déposer et être accueillie dans toute sa singularité."]].map(([n,t,p])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{p}</p></article>)}
    </div></section>
    <section className="freedom-section section shell"><div><p className="eyebrow">La liberté fait partie du voyage</p><h2>Votre retraite,<br /><em>à votre manière.</em></h2></div><div className="freedom-section__copy"><p>Une retraite spirituelle n’est pas un programme à réussir. Entre les pratiques, chacun reste libre de se reposer, de profiter de la maison ou de partir découvrir les environs. Il est possible de vivre pleinement le groupe tout en respectant son propre besoin d’espace.</p><div className="freedom-list"><span>Quad dans les paysages</span><span>Surf sur la côte</span><span>Visite d’Essaouira</span><span>Plage & nature</span><span>Repos à la villa</span><span>Temps pour soi</span></div><p className="freedom-section__closing">Vous pouvez suivre chaque proposition, choisir seulement certains temps ou simplement vous laisser porter. L’essentiel est de revenir à vous.</p><Link href="/rendez-vous?motif=retraite" className="button">Découvrir les prochaines dates <Arrow /></Link></div></section>
    <section className="retreat-conversion"><div className="retreat-conversion__orb" aria-hidden="true" /><div className="shell retreat-conversion__inner"><p className="eyebrow light">Et si la réponse ne se trouvait pas plus loin…</p><h2>Mais dans un espace<br />où vous pouvez enfin<br /><em>vous entendre.</em></h2><div className="retreat-conversion__copy"><p className="retreat-conversion__lead">Vous ne venez pas chercher des réponses toutes faites. Vous venez créer les conditions pour que les vôtres puissent apparaître.</p><p>Pendant quelques jours, le rythme ralentit. Le mental cesse de devoir tout résoudre. Le souffle, le mouvement, les soins, la présence du groupe et la beauté du lieu ouvrent un espace différent — un espace où ce qui semblait confus peut commencer à s’éclairer.</p><p>Il ne s’agit pas de devenir une autre personne. Il s’agit de rencontrer, peut-être plus pleinement que jamais, celle ou celui que vous êtes déjà. Certaines expériences ne s’expliquent pas entièrement : elles se traversent, se ressentent et continuent parfois de résonner bien après le retour.</p><div className="retreat-conversion__questions"><span>Qu’est-ce qui demande à changer ?</span><span>Qu’est-ce que je ne veux plus porter ?</span><span>À quoi ai-je envie de dire oui ?</span></div><Link href="/rendez-vous?motif=retraite" className="button button--light">Sentir si cette retraite est pour moi <Arrow /></Link><small>Un premier échange confidentiel, sans engagement, permet de vérifier si l’expérience correspond à votre situation.</small></div></div></section>
    <Testimonials />
    <section className="ritual"><div className="shell ritual-grid">{["Souffle","Mouvement","Silence","Cercle"].map((x,i)=><div key={x}><span>0{i+1}</span><h3>{x}</h3><p>{["Rebirth et respiration consciente","Kundalini et pratique somatique","Méditation et temps d’intégration","Parole, écoute et lien au groupe"][i]}</p></div>)}</div></section>
    <section className="shell image-credit">Photographies de Villa Maya, Sidi Kaouki — utilisées pour la maquette. Autorisation de diffusion à confirmer avant mise en ligne publique.</section><AppointmentCard /></StandardPage>;
}
